### ISSUE TITLE
Version function breaks on multi-node setup.

### ISSUE THREAD

**Issue by moukoublen** [memcachier/mc#12]
Hello and thanks for this library :sunglasses: 

Right now message object (`msg`) is being reused for both send and receive in `perform` functionality.

https://github.com/memcachier/mc/blob/ae22d23ca7faef4ff0bc8f41fc822239e9693714/client.go#L413-L420

There are some cases (e.g. `Version()`) in which the message is being sent to all nodes.

Because of that after the first send-receive the message `msg` is "mutated" as answer and thus not valid message to send in the next request.

### Steps to reproduce
```bash
memcached -p 11289
memcached -p 11290
memcached -p 11291
```

And run

```golang
c := NewMC("localhost:11289 localhost:11290 localhost:11291", "", "")
vers, err := c.Version()
```

(I will open a PR for that with a fix suggestion)

**Comment by saschat** [comment]
Fixed by #13
