### ISSUE TITLE
Don't unnderstand about connection on overview screen!

### ISSUE THREAD

**Issue by tatthangcntt** [memcachier/mc#18]
I have tried to find documentation that talks about the concepts as shown in the picture. But I still don't quite understand the 2 concepts. Can someone explain to me more about them?

Active Connections: 
New Connection Rate Last Hour
https://gyazo.com/c444d88dcd67ffa155470ab913f541d8

**Comment by saschat** [comment]
This is a MemCachier specific question and has nothing to do with the mc client. I have responded to your contact request and will close this issue.

**Comment by tatthangcntt** [comment]
Ok! sorry about that!

Ngo Tat Thang / Mobile developer
***@***.*** / skype: *tatthang89*

.... Company
0979549021
Số 1 - ngách 99 - Ngõ 337 -  Định Công - Hoàng Mai - Hà Nội
Phong Van - Ba Vi - Ha Noi
<https://htmlsig.com/signatures/0001C8S5BZ>

[image: Twitter]  <https://htmlsig.com/t/000001C9NRD4> [image: Facebook]
<https://htmlsig.com/t/000001C903J8> [image: Google +]
<https://htmlsig.com/t/000001C7EPFA> [image: LinkedIn]
<https://htmlsig.com/t/000001C60DP1> [image: Instagram]
<https://htmlsig.com/t/000001C97FNZ> [image: Skype]
<https://htmlsig.com/t/000001C5TX09> [image: Youtube]
<https://htmlsig.com/t/000001C7KBN5>
