### ISSUE TITLE
How to view index names

### ISSUE THREAD

**Issue by phpip** [memcachier/mc#6]
Memcache has no commands to view the index, but a small amount of index content can be viewed through CacheDump. Can this function be added?

Please see：
https://github.com/Songmu/go-memcached-tool/blob/3b74077e768b5fbe832d82cc3544c1ff0b5736c7/memdtool.go

**Comment by saschat** [comment]
To do a cache dump you require 2 commands, `stats items` and `stats cachedump`.

The `stats items` command is available like so:
```go
c := mc.NewMC("localhost:11211", "username", "password")
c.StatsWithKey("items")
```

In `memcached`, the `stats cachedump` command is **not** implemented for the binary protocol: https://github.com/memcached/memcached/blob/1ac5d63b9b027ad8951323108088ce8a8fcddd29/memcached.c#L1858

**Comment by phpip** [comment]
非常感谢！
