### ISSUE TITLE
No need to perform authentication if either username or password is empty

### ISSUE THREAD

**Issue by mikelca** [memcachier/mc#8]
When sending requests, the current behaviour is always performing authentication when connecting to server. This does not make sense when either the username or the password is empty.

A proposed fix can be adding below checking before https://github.com/memcachier/mc/blob/master/server_conn.go#L91
```
    if sc.username == "" || sc.password == "" {
        return nil
    }
```

**Comment by alevy** [comment]
I think this makes sense
