### ISSUE TITLE
Add support of unix sockets

### ISSUE THREAD

**Issue by VadimIpatov** [memcachier/mc#9]
Currently, it's impossible to connect using unix socket

**Comment by alevy** [comment]
@VadimIpatov pull requests welcome! It would be possible to do this in at least two ways:

1. Create new instance of `mcConn` and `connGen` (arguably those interfaces could be made public to make this possible without changing the library)

2. Modifying the `connect` implementation for `serverConn` by, for example, parsing addresses prefixed with `unix://` as UNIX domain socket URLs and choosing a different protocol for `net.DialTimeout`: https://github.com/memcachier/mc/blob/master/server_conn.go#L78

**Comment by VadimIpatov** [comment]
Hi! I'm done with it: #10 
There are also some fixes and go modules support.

**Comment by alevy** [comment]
Thanks @VadimIpatov!!
